  const elementsData = [
{
num: 1,
symbol: "H",
name: "Hydrogen",
mass: "1.008",
group: 1,
period: 1,
category: "nonmetal",
config: "1s1",
appearance: "Colorless gas",
density: "0.08988 g/L",
melt: "-259.1 °C",
boil: "-252.9 °C",
discovered: "1766 (Cavendish)",
uses: "Rocket fuel, ammonia production, fuel cells"
},
{
num: 2,
symbol: "He",
name: "Helium",
mass: "4.0026",
group: 18,
period: 1,
category: "noble-gas",
config: "1s2",
appearance: "Colorless gas",
density: "0.1786 g/L",
melt: "-272.2 °C",
boil: "-268.9 °C",
discovered: "1868",
uses: "Balloons, cooling superconductors"
},
{
num: 3,
symbol: "Li",
name: "Lithium",
mass: "6.94",
group: 1,
period: 2,
category: "alkali-metal",
config: "[He] 2s1",
appearance: "Silvery",
density: "0.534 g/cm³",
melt: "180.5 °C",
boil: "1342 °C",
discovered: "1817",
uses: "Rechargeable batteries"
},
{
num: 4,
symbol: "Be",
name: "Beryllium",
mass: "9.0122",
group: 2,
period: 2,
category: "alkaline-earth-metal",
config: "[He] 2s2",
appearance: "Gray",
density: "1.85 g/cm³",
melt: "1287 °C",
boil: "2469 °C",
discovered: "1798",
uses: "Aerospace materials"
},
{
num: 5,
symbol: "B",
name: "Boron",
mass: "10.81",
group: 13,
period: 2,
category: "metalloid",
config: "[He] 2s2 2p1",
appearance: "Black-brown",
density: "2.34 g/cm³",
melt: "2076 °C",
boil: "3927 °C",
discovered: "1808",
uses: "Borosilicate glass"
},
{
num: 6,
symbol: "C",
name: "Carbon",
mass: "12.011",
group: 14,
period: 2,
category: "nonmetal",
config: "[He] 2s2 2p2",
appearance: "Black (graphite), colorless (diamond)",
density: "2.26 g/cm³",
melt: "3550 °C",
boil: "4827 °C",
discovered: "Ancient",
uses: "Life, fuels, steel"
},
{
num: 7,
symbol: "N",
name: "Nitrogen",
mass: "14.007",
group: 15,
period: 2,
category: "nonmetal",
config: "[He] 2s2 2p3",
appearance: "Colorless gas",
density: "1.251 g/L",
melt: "-210 °C",
boil: "-196 °C",
discovered: "1772",
uses: "Fertilizers, cryogenics"
},
{
num: 8,
symbol: "O",
name: "Oxygen",
mass: "15.999",
group: 16,
period: 2,
category: "nonmetal",
config: "[He] 2s2 2p4",
appearance: "Colorless gas",
density: "1.429 g/L",
melt: "-218.8 °C",
boil: "-183 °C",
discovered: "1774",
uses: "Breathing, steelmaking"
},
{
num: 9,
symbol: "F",
name: "Fluorine",
mass: "18.998",
group: 17,
period: 2,
category: "halogen",
config: "[He] 2s2 2p5",
appearance: "Pale yellow gas",
density: "1.696 g/L",
melt: "-219.6 °C",
boil: "-188.1 °C",
discovered: "1886",
uses: "Toothpaste, Teflon"
},
{
num: 10,
symbol: "Ne",
name: "Neon",
mass: "20.180",
group: 18,
period: 2,
category: "noble-gas",
config: "[He] 2s2 2p6",
appearance: "Colorless gas",
density: "0.9002 g/L",
melt: "-248.6 °C",
boil: "-246.1 °C",
discovered: "1898",
uses: "Neon signs"
},
{
num: 11,
symbol: "Na",
name: "Sodium",
mass: "22.990",
group: 1,
period: 3,
category: "alkali-metal",
config: "[Ne] 3s1",
appearance: "Silvery white",
density: "0.97 g/cm³",
melt: "97.8 °C",
boil: "883 °C",
discovered: "1807",
uses: "Street lamps, salt"
},
{
num: 12,
symbol: "Mg",
name: "Magnesium",
mass: "24.305",
group: 2,
period: 3,
category: "alkaline-earth-metal",
config: "[Ne] 3s2",
appearance: "Shiny gray",
density: "1.738 g/cm³",
melt: "650 °C",
boil: "1090 °C",
uses: "Fireworks, medicine"
},
{
num: 13,
symbol: "Al",
name: "Aluminium",
mass: "26.982",
group: 13,
period: 3,
category: "post-transition",
config: "[Ne] 3s2 3p1",
appearance: "Silvery",
density: "2.70 g/cm³",
melt: "660 °C",
boil: "2519 °C",
uses: "Packaging, aircraft"
},
{
num: 14,
symbol: "Si",
name: "Silicon",
mass: "28.085",
group: 14,
period: 3,
category: "metalloid",
config: "[Ne] 3s2 3p2",
appearance: "Dark gray",
density: "2.329 g/cm³",
melt: "1414 °C",
boil: "3265 °C",
uses: "Electronics, solar cells"
},
{
num: 15,
symbol: "P",
name: "Phosphorus",
mass: "30.974",
group: 15,
period: 3,
category: "nonmetal",
config: "[Ne] 3s2 3p3",
appearance: "White/red",
density: "1.82 g/cm³",
melt: "44.2 °C (white)",
boil: "280 °C",
uses: "Fertilizers"
},
{
num: 16,
symbol: "S",
name: "Sulfur",
mass: "32.06",
group: 16,
period: 3,
category: "nonmetal",
config: "[Ne] 3s2 3p4",
appearance: "Yellow",
density: "2.07 g/cm³",
melt: "115 °C",
boil: "444.6 °C",
uses: "Sulfuric acid"
},
{
num: 17,
symbol: "Cl",
name: "Chlorine",
mass: "35.45",
group: 17,
period: 3,
category: "halogen",
config: "[Ne] 3s2 3p5",
appearance: "Greenish-yellow gas",
density: "3.2 g/L",
melt: "-101 °C",
boil: "-34 °C",
uses: "Disinfectants"
},
{
num: 18,
symbol: "Ar",
name: "Argon",
mass: "39.948",
group: 18,
period: 3,
category: "noble-gas",
config: "[Ne] 3s2 3p6",
appearance: "Colorless gas",
density: "1.784 g/L",
melt: "-189.4 °C",
boil: "-185.9 °C",
uses: "Light bulbs"
},
{
num: 19,
symbol: "K",
name: "Potassium",
mass: "39.098",
group: 1,
period: 4,
category: "alkali-metal",
config: "[Ar] 4s1",
appearance: "Silvery",
density: "0.862 g/cm³",
melt: "63.5 °C",
boil: "759 °C",
uses: "Fertilizers"
},
{
num: 20,
symbol: "Ca",
name: "Calcium",
mass: "40.078",
group: 2,
period: 4,
category: "alkaline-earth-metal",
config: "[Ar] 4s2",
appearance: "Gray",
density: "1.55 g/cm³",
melt: "842 °C",
boil: "1484 °C",
uses: "Bones, cement"
},
{
num: 21,
symbol: "Sc",
name: "Scandium",
mass: "44.956",
group: 3,
period: 4,
category: "transition-metal",
config: "[Ar] 3d1 4s2",
appearance: "Silvery white",
density: "2.99 g/cm³",
melt: "1541 °C",
boil: "2836 °C",
uses: "Aerospace alloys"
},
{
num: 22,
symbol: "Ti",
name: "Titanium",
mass: "47.867",
group: 4,
period: 4,
category: "transition-metal",
config: "[Ar] 3d2 4s2",
appearance: "Silvery gray",
density: "4.506 g/cm³",
melt: "1668 °C",
boil: "3287 °C",
uses: "Aircraft, implants"
},
{
num: 23,
symbol: "V",
name: "Vanadium",
mass: "50.942",
group: 5,
period: 4,
category: "transition-metal",
config: "[Ar] 3d3 4s2",
appearance: "Silvery gray",
density: "6.11 g/cm³",
melt: "1910 °C",
boil: "3407 °C",
uses: "Steel alloys"
},
{
num: 24,
symbol: "Cr",
name: "Chromium",
mass: "51.996",
group: 6,
period: 4,
category: "transition-metal",
config: "[Ar] 3d5 4s1",
appearance: "Silvery",
density: "7.19 g/cm³",
melt: "1907 °C",
boil: "2671 °C",
uses: "Stainless steel"
},
{
num: 25,
symbol: "Mn",
name: "Manganese",
mass: "54.938",
group: 7,
period: 4,
category: "transition-metal",
config: "[Ar] 3d5 4s2",
appearance: "Gray",
density: "7.21 g/cm³",
melt: "1246 °C",
boil: "2061 °C",
uses: "Steel, batteries"
},
{
num: 26,
symbol: "Fe",
name: "Iron",
mass: "55.845",
group: 8,
period: 4,
category: "transition-metal",
config: "[Ar] 3d6 4s2",
appearance: "Metallic gray",
density: "7.87 g/cm³",
melt: "1538 °C",
boil: "2862 °C",
uses: "Construction, tools"
},
{
num: 27,
symbol: "Co",
name: "Cobalt",
mass: "58.933",
group: 9,
period: 4,
category: "transition-metal",
config: "[Ar] 3d7 4s2",
appearance: "Hard gray",
density: "8.90 g/cm³",
melt: "1495 °C",
boil: "2927 °C",
uses: "Batteries, magnets"
},
{
num: 28,
symbol: "Ni",
name: "Nickel",
name: "Nickel",
mass: "58.693",
group: 10,
period: 4,
category: "transition-metal",
config: "[Ar] 3d8 4s2",
appearance: "Silvery white",
density: "8.908 g/cm³",
melt: "1455 °C",
boil: "2913 °C",
uses: "Coins, batteries"
},
{
num: 29,
symbol: "Cu",
name: "Copper",
mass: "63.546",
group: 11,
period: 4,
category: "transition-metal",
config: "[Ar] 3d10 4s1",
appearance: "Reddish",
density: "8.96 g/cm³",
melt: "1085 °C",
boil: "2562 °C",
uses: "Wiring, coins"
},
{
num: 30,
symbol: "Zn",
name: "Zinc",
mass: "65.38",
group: 12,
period: 4,
category: "transition-metal",
config: "[Ar] 3d10 4s2",
appearance: "Bluish silver",
density: "7.14 g/cm³",
melt: "419.5 °C",
boil: "907 °C",
uses: "Galvanization"
},
{
num: 31,
symbol: "Ga",
name: "Gallium",
mass: "69.723",
group: 13,
period: 4,
category: "post-transition",
config: "[Ar] 3d10 4s2 4p1",
appearance: "Silvery blue",
density: "5.91 g/cm³",
melt: "29.7 °C",
boil: "2400 °C",
discovered: "1875",
uses: "Thermometers, semiconductors"
},
{
num: 32,
symbol: "Ge",
name: "Germanium",
mass: "72.630",
group: 14,
period: 4,
category: "metalloid",
config: "[Ar] 3d10 4s2 4p2",
appearance: "Grayish white",
density: "5.32 g/cm³",
melt: "938.3 °C",
boil: "2820 °C",
discovered: "1886",
uses: "Infrared optics, semiconductors"
},
{
num: 33,
symbol: "As",
name: "Arsenic",
mass: "74.922",
group: 15,
period: 4,
category: "metalloid",
config: "[Ar] 3d10 4s2 4p3",
appearance: "Metallic gray",
density: "5.73 g/cm³",
melt: "817 °C (sublimes)",
boil: "614 °C",
discovered: "Ancient",
uses: "Electronics, pesticides"
},
{
num: 34,
symbol: "Se",
name: "Selenium",
mass: "78.971",
group: 16,
period: 4,
category: "nonmetal",
config: "[Ar] 3d10 4s2 4p4",
appearance: "Red or gray",
density: "4.81 g/cm³",
melt: "221 °C",
boil: "685 °C",
uses: "Glass coloring, photocopiers"
},
{
num: 35,
symbol: "Br",
name: "Bromine",
mass: "79.904",
group: 17,
period: 4,
category: "halogen",
config: "[Ar] 3d10 4s2 4p5",
appearance: "Red-brown liquid",
density: "3.1 g/cm³",
melt: "-7.2 °C",
boil: "58.8 °C",
uses: "Flame retardants"
},
{
num: 36,
symbol: "Kr",
name: "Krypton",
mass: "83.798",
group: 18,
period: 4,
category: "noble-gas",
config: "[Ar] 3d10 4s2 4p6",
appearance: "Colorless gas",
density: "3.749 g/L",
melt: "-157.4 °C",
boil: "-153.2 °C",
uses: "Lighting"
},
{
num: 37,
symbol: "Rb",
name: "Rubidium",
mass: "85.468",
group: 1,
period: 5,
category: "alkali-metal",
config: "[Kr] 5s1",
appearance: "Soft silvery",
density: "1.53 g/cm³",
melt: "39.3 °C",
boil: "688 °C",
uses: "Research, electronics"
},
{
num: 38,
symbol: "Sr",
name: "Strontium",
mass: "87.62",
group: 2,
period: 5,
category: "alkaline-earth-metal",
config: "[Kr] 5s2",
appearance: "Soft yellowish",
density: "2.64 g/cm³",
melt: "777 °C",
boil: "1377 °C",
uses: "Fireworks (red), magnets"
},
{
num: 39,
symbol: "Y",
name: "Yttrium",
mass: "88.906",
group: 3,
period: 5,
category: "transition-metal",
config: "[Kr] 4d1 5s2",
appearance: "Silver-metallic",
density: "4.47 g/cm³",
melt: "1526 °C",
boil: "3345 °C",
uses: "LEDs, lasers"
},
{
num: 40,
symbol: "Zr",
name: "Zirconium",
mass: "91.224",
group: 4,
period: 5,
category: "transition-metal",
config: "[Kr] 4d2 5s2",
appearance: "Gray-white",
density: "6.52 g/cm³",
melt: "1855 °C",
boil: "4377 °C",
uses: "Nuclear reactors"
},
{
num: 41,
symbol: "Nb",
name: "Niobium",
mass: "92.906",
group: 5,
period: 5,
category: "transition-metal",
config: "[Kr] 4d4 5s1",
appearance: "Gray",
density: "8.57 g/cm³",
melt: "2468 °C",
boil: "4744 °C",
uses: "Superconductors"
},
{
num: 42,
symbol: "Mo",
name: "Molybdenum",
mass: "95.95",
group: 6,
period: 5,
category: "transition-metal",
config: "[Kr] 4d5 5s1",
appearance: "Silver",
density: "10.22 g/cm³",
melt: "2623 °C",
boil: "4639 °C",
uses: "Steel alloys"
},
{
num: 43,
symbol: "Tc",
name: "Technetium",
mass: "98",
group: 7,
period: 5,
category: "transition-metal",
config: "[Kr] 4d5 5s2",
appearance: "Gray",
density: "11 g/cm³",
melt: "2157 °C",
boil: "4265 °C",
uses: "Medical imaging"
},
{
num: 44,
symbol: "Ru",
name: "Ruthenium",
mass: "101.07",
group: 8,
period: 5,
category: "transition-metal",
config: "[Kr] 4d7 5s1",
appearance: "Silvery white",
density: "12.37 g/cm³",
melt: "2334 °C",
boil: "4150 °C",
uses: "Electronics"
},
{
num: 45,
symbol: "Rh",
name: "Rhodium",
mass: "102.91",
group: 9,
period: 5,
category: "transition-metal",
config: "[Kr] 4d8 5s1",
appearance: "Silvery white",
density: "12.41 g/cm³",
melt: "1964 °C",
boil: "3695 °C",
uses: "Catalytic converters"
},
{
num: 46,
symbol: "Pd",
name: "Palladium",
mass: "106.42",
group: 10,
period: 5,
category: "transition-metal",
config: "[Kr] 4d10",
appearance: "Silvery white",
density: "12.02 g/cm³",
melt: "1555 °C",
boil: "2963 °C",
uses: "Electronics, jewelry"
},
{
num: 47,
symbol: "Ag",
name: "Silver",
mass: "107.87",
group: 11,
period: 5,
category: "transition-metal",
config: "[Kr] 4d10 5s1",
appearance: "Shiny white metallic",
density: "10.49 g/cm³",
melt: "961.8 °C",
boil: "2162 °C",
uses: "Jewelry, electronics"
},
{
num: 48,
symbol: "Cd",
name: "Cadmium",
mass: "112.41",
group: 12,
period: 5,
category: "transition-metal",
config: "[Kr] 4d10 5s2",
appearance: "Silvery white",
density: "8.65 g/cm³",
melt: "321.1 °C",
boil: "767 °C",
uses: "Batteries"
},
{
num: 49,
symbol: "In",
name: "Indium",
mass: "114.82",
group: 13,
period: 5,
category: "post-transition",
config: "[Kr] 4d10 5s2 5p1",
appearance: "Soft silvery",
density: "7.31 g/cm³",
melt: "156.6 °C",
boil: "2072 °C",
uses: "Touchscreens, LEDs"
},
{
num: 50,
symbol: "Sn",
name: "Tin",
mass: "118.71",
group: 14,
period: 5,
category: "post-transition",
config: "[Kr] 4d10 5s2 5p2",
appearance: "Silvery white",
density: "7.31 g/cm³",
melt: "231.9 °C",
boil: "2602 °C",
uses: "Cans, solder"
},
{
num: 51,
symbol: "Sb",
name: "Antimony",
mass: "121.76",
group: 15,
period: 5,
category: "metalloid",
config: "[Kr] 4d10 5s2 5p3",
appearance: "Silvery gray",
density: "6.697 g/cm³",
melt: "631 °C",
boil: "1587 °C",
uses: "Flame retardants"
},
{
num: 52,
symbol: "Te",
name: "Tellurium",
mass: "127.60",
group: 16,
period: 5,
category: "metalloid",
config: "[Kr] 4d10 5s2 5p4",
appearance: "Silver-white",
density: "6.24 g/cm³",
melt: "449.5 °C",
boil: "988 °C",
uses: "Solar panels"
},
{
num: 53,
symbol: "I",
name: "Iodine",
mass: "126.90",
group: 17,
period: 5,
category: "halogen",
config: "[Kr] 4d10 5s2 5p5",
appearance: "Purple solid",
density: "4.93 g/cm³",
melt: "113.7 °C",
boil: "184.3 °C",
uses: "Medicine, disinfectants"
},
{
num: 54,
symbol: "Xe",
name: "Xenon",
mass: "131.29",
group: 18,
period: 5,
category: "noble-gas",
config: "[Kr] 4d10 5s2 5p6",
appearance: "Colorless gas",
density: "5.894 g/L",
melt: "-111.8 °C",
boil: "-108.1 °C",
uses: "Lamps, ion engines"
},
{
num: 55,
symbol: "Cs",
name: "Cesium",
mass: "132.91",
group: 1,
period: 6,
category: "alkali-metal",
config: "[Xe] 6s1",
appearance: "Gold-colored soft metal",
density: "1.93 g/cm³",
melt: "28.5 °C",
boil: "671 °C",
uses: "Atomic clocks"
},
{
num: 56,
symbol: "Ba",
name: "Barium",
mass: "137.33",
group: 2,
period: 6,
category: "alkaline-earth-metal",
config: "[Xe] 6s2",
appearance: "Silvery white",
density: "3.51 g/cm³",
melt: "727 °C",
boil: "1870 °C",
uses: "Fireworks (green)"
},
{
num: 57,
symbol: "La",
name: "Lanthanum",
mass: "138.91",
group: 3,
period: 6,
category: "lanthanide",
config: "[Xe] 5d1 6s2",
appearance: "Silvery white",
density: "6.15 g/cm³",
melt: "920 °C",
boil: "3464 °C",
uses: "Camera lenses"
},
{
num: 58,
symbol: "Ce",
name: "Cerium",
mass: "140.12",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f1 5d1 6s2",
appearance: "Silvery",
density: "6.77 g/cm³",
melt: "798 °C",
boil: "3443 °C",
uses: "Lighter flints"
},
{
num: 59,
symbol: "Pr",
name: "Praseodymium",
mass: "140.91",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f3 6s2",
appearance: "Silvery",
density: "6.77 g/cm³",
melt: "931 °C",
boil: "3520 °C",
uses: "Magnets, alloys"
},
{
num: 60,
symbol: "Nd",
name: "Neodymium",
mass: "144.24",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f4 6s2",
appearance: "Silvery",
density: "7.01 g/cm³",
melt: "1024 °C",
boil: "3074 °C",
uses: "Strong magnets"
},
{
num: 61,
symbol: "Pm",
name: "Promethium",
mass: "145",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f5 6s2",
appearance: "Silvery (predicted)",
density: "7.26 g/cm³ (estimated)",
melt: "1100 °C (estimated)",
boil: "3000 °C (estimated)",
discovered: "1945",
uses: "Research, luminous paint (historic/proposed)"
},
{
num: 62,
symbol: "Sm",
name: "Samarium",
mass: "150.36",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f6 6s2",
appearance: "Silvery white",
density: "7.52 g/cm³",
melt: "1072 °C",
boil: "1900 °C (approx)",
discovered: "1879",
uses: "Magnets, nuclear control rods"
},
{
num: 63,
symbol: "Eu",
name: "Europium",
mass: "151.96",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f7 6s2",
appearance: "Silvery white",
density: "5.243 g/cm³",
melt: "821 °C",
boil: "1529 °C",
discovered: "1901",
uses: "Phosphors, LEDs"
},
{
num: 64,
symbol: "Gd",
name: "Gadolinium",
mass: "157.25",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f7 5d1 6s2",
appearance: "Silvery white",
density: "7.90 g/cm³",
melt: "1313 °C",
boil: "3000 °C (approx)",
discovered: "1880",
uses: "MRI contrast agents, magnets"
},
{
num: 65,
symbol: "Tb",
name: "Terbium",
mass: "158.93",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f9 6s2",
appearance: "Silvery",
density: "8.23 g/cm³",
melt: "1356 °C",
boil: "3000 °C (approx)",
discovered: "1843",
uses: "Phosphors, sensors"
},
{
num: 66,
symbol: "Dy",
name: "Dysprosium",
mass: "162.50",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f10 6s2",
appearance: "Silvery white",
density: "8.54 g/cm³",
melt: "1412 °C",
boil: "2567 °C",
discovered: "1886",
uses: "Magnets, nuclear reactors"
},
{
num: 67,
symbol: "Ho",
name: "Holmium",
mass: "164.93",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f11 6s2",
appearance: "Silvery white",
density: "8.79 g/cm³",
melt: "1474 °C",
boil: "2700 °C (approx)",
discovered: "1878",
uses: "Lasers, magnets"
},
{
num: 68,
symbol: "Er",
name: "Erbium",
mass: "167.26",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f12 6s2",
appearance: "Silvery white",
density: "9.07 g/cm³",
melt: "1529 °C",
boil: "2868 °C",
discovered: "1843",
uses: "Optical amplifiers, lasers"
},
{
num: 69,
symbol: "Tm",
name: "Thulium",
mass: "168.93",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f13 6s2",
appearance: "Silvery gray",
density: "9.32 g/cm³",
melt: "1545 °C",
boil: "1950 °C (approx)",
discovered: "1879",
uses: "Lasers, portable X-ray devices"
},
{
num: 70,
symbol: "Yb",
name: "Ytterbium",
mass: "173.05",
group: null,
period: 6,
category: "lanthanide",
config: "[Xe] 4f14 6s2",
appearance: "Shiny silver",
density: "6.90 g/cm³",
melt: "824 °C",
boil: "1196 °C",
discovered: "1878",
uses: "Clocks, lasers"
},
{
num: 71,
symbol: "Lu",
name: "Lutetium",
mass: "174.97",
group: 3,
period: 6,
category: "lanthanide",
config: "[Xe] 4f14 5d1 6s2",
appearance: "Silvery white",
density: "9.84 g/cm³",
melt: "1663 °C",
boil: "3402 °C",
discovered: "1907",
uses: "PET scanners, catalysts"
},
{
num: 72,
symbol: "Hf",
name: "Hafnium",
mass: "178.49",
group: 4,
period: 6,
category: "transition-metal",
config: "[Xe] 4f14 5d2 6s2",
appearance: "Gray",
density: "13.31 g/cm³",
melt: "2233 °C",
boil: "4603 °C",
discovered: "1923",
uses: "Nuclear control rods, alloys"
},
{
num: 73,
symbol: "Ta",
name: "Tantalum",
mass: "180.95",
group: 5,
period: 6,
category: "transition-metal",
config: "[Xe] 4f14 5d3 6s2",
appearance: "Blue-gray metal",
density: "16.69 g/cm³",
melt: "3017 °C",
boil: "5458 °C",
discovered: "1802",
uses: "Capacitors, surgical implants"
},
{
num: 74,
symbol: "W",
name: "Tungsten",
mass: "183.84",
group: 6,
period: 6,
category: "transition-metal",
config: "[Xe] 4f14 5d4 6s2",
appearance: "Grayish-white",
density: "19.25 g/cm³",
melt: "3422 °C",
boil: "5555 °C",
discovered: "1783",
uses: "Filaments, cutting tools"
},
{
num: 75,
symbol: "Re",
name: "Rhenium",
mass: "186.21",
group: 7,
period: 6,
category: "transition-metal",
config: "[Xe] 4f14 5d5 6s2",
appearance: "Silvery",
density: "21.02 g/cm³",
melt: "3186 °C",
boil: "5596 °C",
discovered: "1925",
uses: "Aerospace alloys, catalysts"
},
{
num: 76,
symbol: "Os",
name: "Osmium",
mass: "190.23",
group: 8,
period: 6,
category: "transition-metal",
config: "[Xe] 4f14 5d6 6s2",
appearance: "Blue-gray metal",
density: "22.59 g/cm³",
melt: "3045 °C",
boil: "5027 °C",
discovered: "1803",
uses: "Alloys, precision instruments"
},
{
num: 77,
symbol: "Ir",
name: "Iridium",
mass: "192.22",
group: 9,
period: 6,
category: "transition-metal",
config: "[Xe] 4f14 5d7 6s2",
appearance: "Silvery white",
density: "22.56 g/cm³",
melt: "2446 °C",
boil: "4428 °C",
discovered: "1803",
uses: "Spark plugs, crucibles"
},
{
num: 78,
symbol: "Pt",
name: "Platinum",
mass: "195.08",
group: 10,
period: 6,
category: "transition-metal",
config: "[Xe] 4f14 5d9 6s1",
appearance: "Silvery white",
density: "21.45 g/cm³",
melt: "1772 °C",
boil: "3825 °C",
discovered: "Ancient",
uses: "Catalysts, jewelry"
},
{
num: 79,
symbol: "Au",
name: "Gold",
mass: "196.97",
group: 11,
period: 6,
category: "transition-metal",
config: "[Xe] 4f14 5d10 6s1",
appearance: "Yellow metal",
density: "19.32 g/cm³",
melt: "1064 °C",
boil: "2856 °C",
discovered: "Ancient",
uses: "Jewelry, electronics"
},
{
num: 80,
symbol: "Hg",
name: "Mercury",
mass: "200.59",
group: 12,
period: 6,
category: "transition-metal",
config: "[Xe] 4f14 5d10 6s2",
appearance: "Silvery liquid",
density: "13.534 g/cm³",
melt: "-38.83 °C",
boil: "356.73 °C",
discovered: "Ancient",
uses: "Thermometers (historic), lighting"
},
{
num: 81,
symbol: "Tl",
name: "Thallium",
mass: "204.38",
group: 13,
period: 6,
category: "post-transition",
config: "[Xe] 4f14 5d10 6s2 6p1",
appearance: "Silvery white",
density: "11.85 g/cm³",
melt: "304 °C",
boil: "1473 °C",
discovered: "1861",
uses: "Electronics, alloys (research uses)"
},
{
num: 82,
symbol: "Pb",
name: "Lead",
mass: "207.2",
group: 14,
period: 6,
category: "post-transition",
config: "[Xe] 4f14 5d10 6s2 6p2",
appearance: "Bluish-gray metal",
density: "11.34 g/cm³",
melt: "327.5 °C",
boil: "1749 °C",
discovered: "Ancient",
uses: "Batteries, shielding, pipes (historic)"
},
{
num: 83,
symbol: "Bi",
name: "Bismuth",
mass: "208.98",
group: 15,
period: 6,
category: "post-transition",
config: "[Xe] 4f14 5d10 6s2 6p3",
appearance: "Silvery white with pink tint",
density: "9.78 g/cm³",
melt: "271.4 °C",
boil: "1564 °C",
discovered: "Ancient",
uses: "Alloys, medicine"
},
{
num: 84,
symbol: "Po",
name: "Polonium",
mass: "209",
group: 16,
period: 6,
category: "metalloid",
config: "[Xe] 4f14 5d10 6s2 6p4",
appearance: "Silvery (radioactive, rare)",
density: "9.32 g/cm³ (approx)",
melt: "254 °C",
boil: "962 °C (approx)",
discovered: "1898",
uses: "Research, heat sources (radioactive)"
},
{
num: 85,
symbol: "At",
name: "Astatine",
mass: "210",
group: 17,
period: 6,
category: "halogen",
config: "[Xe] 4f14 5d10 6s2 6p5",
appearance: "Unknown (likely metallic/halogen-like)",
density: "Estimated",
melt: "Estimated",
boil: "Estimated",
discovered: "1940",
uses: "Research (very rare, radioactive)"
},
{
num: 86,
symbol: "Rn",
name: "Radon",
mass: "222",
group: 18,
period: 6,
category: "noble-gas",
config: "[Xe] 4f14 5d10 6s2 6p6",
appearance: "Colorless gas",
density: "9.73 g/L",
melt: "-71 °C",
boil: "-61.8 °C",
discovered: "1900",
uses: "Research, radiotherapy (limited)"
},
{
num: 87,
symbol: "Fr",
name: "Francium",
mass: "223",
group: 1,
period: 7,
category: "alkali-metal",
config: "[Rn] 7s1",
appearance: "Unknown (very rare, predicted silvery)",
density: "Estimated",
melt: "Estimated",
boil: "Estimated",
discovered: "1939",
uses: "Research (very rare)"
},
{
num: 88,
symbol: "Ra",
name: "Radium",
mass: "226",
group: 2,
period: 7,
category: "alkaline-earth-metal",
config: "[Rn] 7s2",
appearance: "Silvery white (radioactive)",
density: "5.5 g/cm³ (approx)",
melt: "700 °C (approx)",
boil: "1140 °C (approx)",
discovered: "1898",
uses: "Radiotherapy (historic), research"
},
{
num: 89,
symbol: "Ac",
name: "Actinium",
mass: "227",
group: 3,
period: 7,
category: "actinide",
config: "[Rn] 6d1 7s2",
appearance: "Silvery metallic (radioactive)",
density: "10.07 g/cm³",
melt: "1050 °C (approx)",
boil: "3200 °C (approx)",
discovered: "1899",
uses: "Research, neutron sources"
},
{
num: 90,
symbol: "Th",
name: "Thorium",
mass: "232.04",
group: null,
period: 7,
category: "actinide",
config: "[Rn] 6d2 7s2",
appearance: "Silvery",
density: "11.72 g/cm³",
melt: "1750 °C",
boil: "4790 °C",
discovered: "1829",
uses: "Nuclear fuel research"
},
{
  num: 91,
  symbol: "Pa",
  name: "Protactinium",
  mass: "231.03588",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f2 6d1 7s2",
  uses: "Used in material science and geochemical research.",
  density: "15.37 g/cm³",
  melt: "1568 °C",
  boil: "4027 °C",
  appearance: "Silvery metallic, highly radioactive"
},
{
  num: 92,
  symbol: "U",
  name: "Uranium",
  mass: "238.02891",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f3 6d1 7s2",
  uses: "Nuclear fuel, armor-piercing ammunition.",
  density: "19.1 g/cm³",
  melt: "1132 °C",
  boil: "4131 °C",
  appearance: "Silvery gray, radioactive"
},
{
  num: 93,
  symbol: "Np",
  name: "Neptunium",
  mass: "237",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f4 6d1 7s2",
  uses: "Neutron detectors, scientific research.",
  density: "20.45 g/cm³",
  melt: "639 °C",
  boil: "4174 °C",
  appearance: "Silvery metallic"
},
{
  num: 94,
  symbol: "Pu",
  name: "Plutonium",
  mass: "244",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f6 7s2",
  uses: "Nuclear fuel, spacecraft power sources.",
  density: "19.84 g/cm³",
  melt: "640 °C",
  boil: "3230 °C",
  appearance: "Silvery, tarnishes quickly"
},
{
  num: 95,
  symbol: "Am",
  name: "Americium",
  mass: "243",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f7 7s2",
  uses: "Used in smoke detectors and industrial gauges.",
  density: "12 g/cm³",
  melt: "1176 °C",
  boil: "2607 °C",
  appearance: "Silvery white"
},
{
  num: 96,
  symbol: "Cm",
  name: "Curium",
  mass: "247",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f7 6d1 7s2",
  uses: "Radiation sources and scientific research.",
  density: "13.51 g/cm³",
  melt: "1340 °C",
  boil: "3110 °C",
  appearance: "Silvery metallic"
},
{
  num: 97,
  symbol: "Bk",
  name: "Berkelium",
  mass: "247",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f9 7s2",
  uses: "Only for research; no commercial applications.",
  density: "14.78 g/cm³",
  melt: "986 °C",
  boil: "2627 °C",
  appearance: "Silvery"
},
{
  num: 98,
  symbol: "Cf",
  name: "Californium",
  mass: "251",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f10 7s2",
  uses: "Used in neutron moisture gauges and mining exploration.",
  density: "15.1 g/cm³",
  melt: "900 °C",
  boil: "Unknown",
  appearance: "Silvery white, radioactive"
},
{
  num: 99,
  symbol: "Es",
  name: "Einsteinium",
  mass: "252",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f11 7s2",
  uses: "Scientific research only.",
  density: "8.84 g/cm³",
  melt: "860 °C",
  boil: "Unknown",
  appearance: "Silvery"
},
{
  num: 100,
  symbol: "Fm",
  name: "Fermium",
  mass: "257",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f12 7s2",
  uses: "No commercial use; research only.",
  density: "Unknown",
  melt: "1527 °C",
  boil: "Unknown",
  appearance: "Metallic (assumed)"
},
{
  num: 101,
  symbol: "Md",
  name: "Mendelevium",
  mass: "258",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f13 7s2",
  uses: "Scientific research.",
  density: "Unknown",
  melt: "827 °C",
  boil: "Unknown",
  appearance: "Metallic (assumed)"
},
{
  num: 102,
  symbol: "No",
  name: "Nobelium",
  mass: "259",
  group: null,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f14 7s2",
  uses: "Research only.",
  density: "Unknown",
  melt: "827 °C",
  boil: "Unknown",
  appearance: "Metallic"
},
{
  num: 103,
  symbol: "Lr",
  name: "Lawrencium",
  mass: "266",
  group: 3,
  period: 7,
  category: "actinide",
  config: "[Rn] 5f14 7s2 7p1",
  uses: "Research only.",
  density: "Unknown",
  melt: "1900 °C",
  boil: "Unknown",
  appearance: "Metallic"
},
{
  num: 104,
  symbol: "Rf",
  name: "Rutherfordium",
  mass: "267",
  group: 4,
  period: 7,
  category: "transition",
  config: "[Rn] 5f14 6d2 7s2",
  uses: "Scientific research only.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metallic (synthetic)"
},
{
  num: 105,
  symbol: "Db",
  name: "Dubnium",
  mass: "268",
  group: 5,
  period: 7,
  category: "transition",
  config: "[Rn] 5f14 6d3 7s2",
  uses: "Research.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metallic"
},
{
  num: 106,
  symbol: "Sg",
  name: "Seaborgium",
  mass: "269",
  group: 6,
  period: 7,
  category: "transition",
  config: "[Rn] 5f14 6d4 7s2",
  uses: "Research.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metallic"
},
{
  num: 107,
  symbol: "Bh",
  name: "Bohrium",
  mass: "270",
  group: 7,
  period: 7,
  category: "transition",
  config: "[Rn] 5f14 6d5 7s2",
  uses: "Research.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metallic"
},
{
  num: 108,
  symbol: "Hs",
  name: "Hassium",
  mass: "270",
  group: 8,
  period: 7,
  category: "transition",
  config: "[Rn] 5f14 6d6 7s2",
  uses: "Research.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metallic"
},
{
  num: 109,
  symbol: "Mt",
  name: "Meitnerium",
  mass: "278",
  group: 9,
  period: 7,
  category: "transition",
  config: "[Rn] 5f14 6d7 7s2",
  uses: "Research.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metallic"
},
{
  num: 110,
  symbol: "Ds",
  name: "Darmstadtium",
  mass: "281",
  group: 10,
  period: 7,
  category: "transition",
  config: "[Rn] 5f14 6d8 7s2",
  uses: "Research.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metallic"
},
{
  num: 111,
  symbol: "Rg",
  name: "Roentgenium",
  mass: "282",
  group: 11,
  period: 7,
  category: "transition",
  config: "[Rn] 5f14 6d9 7s2",
  uses: "Research.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metallic"
},
{
  num: 112,
  symbol: "Cn",
  name: "Copernicium",
  mass: "285",
  group: 12,
  period: 7,
  category: "post-transition",
  config: "[Rn] 5f14 6d10 7s2",
  uses: "Research.",
  density: "23.7 g/cm³ (predicted)",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Possibly liquid at room temperature"
},
{
  num: 113,
  symbol: "Nh",
  name: "Nihonium",
  mass: "286",
  group: 13,
  period: 7,
  category: "post-transition",
  config: "[Rn] 5f14 6d10 7s2 7p1",
  uses: "Research only.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metallic (predicted)"
},
{
  num: 114,
  symbol: "Fl",
  name: "Flerovium",
  mass: "289",
  group: 14,
  period: 7,
  category: "post-transition",
  config: "[Rn] 5f14 6d10 7s2 7p2",
  uses: "Research only.",
  density: "14 g/cm³ (predicted)",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Soft metal (predicted)"
},
{
  num: 115,
  symbol: "Mc",
  name: "Moscovium",
  mass: "290",
  group: 15,
  period: 7,
  category: "post-transition",
  config: "[Rn] 5f14 6d10 7s2 7p3",
  uses: "Scientific research.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metal (synthetic)"
},
{
  num: 116,
  symbol: "Lv",
  name: "Livermorium",
  mass: "293",
  group: 16,
  period: 7,
  category: "post-transition",
  config: "[Rn] 5f14 6d10 7s2 7p4",
  uses: "Research only.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Metallic (synthetic)"
},
{
  num: 117,
  symbol: "Ts",
  name: "Tennessine",
  mass: "294",
  group: 17,
  period: 7,
  category: "halogen",
  config: "[Rn] 5f14 6d10 7s2 7p5",
  uses: "Scientific research only.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Predicted: solid halogen"
},
{
  num: 118,
  symbol: "Og",
  name: "Oganesson",
  mass: "294",
  group: 18,
  period: 7,
  category: "noble",
  config: "[Rn] 5f14 6d10 7s2 7p6",
  uses: "Scientific research.",
  density: "Unknown",
  melt: "Unknown",
  boil: "Unknown",
  appearance: "Likely a solid, not a gas"
}
];

const categoryClass = cat => cat || '';

const table = document.getElementById('table');
elements.forEach(el => {
  const div = document.createElement('div');
  div.className = 'element ' + categoryClass(el.category);
  div.dataset.num = el.num;
  div.dataset.symbol = el.symbol.toLowerCase();
  div.dataset.name = el.name.toLowerCase();
  div.dataset.category = el.category;
  div.innerHTML = `
    <div class="top"><div class="num">${el.num}</div><div class="mass">${el.mass}</div></div>
    <div class="symbol">${el.symbol}</div>
    <div class="nameSmall">${el.name}</div>
  `;
  div.addEventListener('click',()=>openPopup(el));
  table.appendChild(div);
});

// Search & filter
document.getElementById('search').addEventListener('input', applyFilters);
document.getElementById('filter').addEventListener('change', applyFilters);
function applyFilters(){
  const q = document.getElementById('search').value.toLowerCase();
  const cat = document.getElementById('filter').value;
  document.querySelectorAll('.element').forEach(el=>{
    const matchesQuery = !q || el.dataset.name.includes(q) || el.dataset.symbol.includes(q) || el.dataset.num===q;
    const matchesCat = cat==='all' || el.dataset.category===cat;
    el.style.display = (matchesQuery && matchesCat) ? 'flex' : 'none';
  });
}

// Popup
const popup=document.getElementById('popup');
const pName=document.getElementById('pName');
const pSymbolNum=document.getElementById('pSymbolNum');
const pMass=document.getElementById('pMass');
const pGroup=document.getElementById('pGroup');
const pConfig=document.getElementById('pConfig');
const pUses=document.getElementById('pUses');
const close=document.getElementById('close');
function openPopup(el){
  pName.textContent = `${el.name} (${el.symbol})`;
  pSymbolNum.textContent = `${el.symbol} • Atomic number ${el.num}`;
  pMass.textContent = `Standard atomic mass: ${el.mass}`;
  pGroup.textContent = `Group: ${el.group || '-'}  |  Period: ${el.period}`;
  pConfig.textContent = `Electron configuration: ${el.config || '-'}`;
  pUses.textContent = `Uses / Notes: ${el.uses || '-'}`;
  popup.style.display='flex';
}
close.addEventListener('click',()=>popup.style.display='none');
popup.addEventListener('click',(e)=>{if(e.target===popup)popup.style.display='none';});

// Theme toggle
document.getElementById('theme').addEventListener('click',()=>{
  const root=document.documentElement;
  root.setAttribute('data-theme', root.getAttribute('data-theme')==='dark'?'light':'dark');
});
